/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import ProductCustomization from '../product-customization';
import { IProductCustomizationData } from '../product-customization.data';
import { IProductCustomizationConfig, IProductCustomizationProps } from '../product-customization.props.autogenerated';

const mockData: IProductCustomizationData = {
    actionResponse: {
        text: 'Sample Response Data'
    }
};

const mockConfig: IProductCustomizationConfig = {
    showText: 'product-customization'
};

const mockActions = {};

describe('ProductCustomization', () => {
    let moduleProps: IProductCustomizationProps<IProductCustomizationData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IProductCustomizationProps<IProductCustomizationData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<ProductCustomization {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
